### PR TITLE
Schedule component

### PR DESCRIPTION
**Pull request by imnotteixeira**
Missing:
* Concurrent events layout
* events descriptions
* Title styling as per mockup

### CODE REVIEW

**Comment by pedromsfernandes** [comment]
The build is failing on the activity template... since we don't have a mock-up we might as well remove it.

image

**Comment by pedromsfernandes** [comment]
Looks good, I'd just remove the links on each event since we don't have an event page anymore.

**Comment by imnotteixeira** [comment]
> Looks good, I'd just remove the links on each event since we don't have an event page anymore.

There won't be event descriptions then?

**Comment by pedromsfernandes** [comment]
> There won't be event descriptions then?
If we can't fit them in the schedule, no

**Review by pedromsfernandes — APPROVED** [review]

**Review by pedromsfernandes — APPROVED** [review]

**Review by CiscoFrisco — APPROVED** [review]

**Pull request merged**
