### PR TITLE
Hackathon page

### PR DESCRIPTION
**Pull request by pedromsfernandes**
Missing:

- [x] Prize pictures
- [x] Updated text
- [x] General layout component
- [ ] Correct regulation and sign in links

Note that the winners section will obviously not be displayed initially (we only have to omit the field from the query), but I've included it just to check how it looks.

### CODE REVIEW

**Comment by CiscoFrisco** [comment]
Looks good! I Only have a couple of notes.

- The first prize in some mobile phone models overflows

i.e. Galaxy S5

image

- The Regulation link when hovered shows the default underline and color of link components. Setting the text-decoration to "none" and color to one of the primary colors of global.css would probably be best here.
- Lastly, the winner section shows some bullet points. However, since this one is not to be displayed until after the event, it can be changed later.

**Comment by pedrogneto** [comment]
Seems good, I only have two notes:
When hovering the "Regulation" button, it's the default "blue underlined text" that I don't particularly like
Still about the "Regulation" button, I personally prefer it when the <a> tags are around the div instead of the inner text although this is being picky

**Comment by pedromsfernandes** [comment]
I've fixed the link and prize issues.

> Lastly, the winner section shows some bullet points. However, since this one is not to be displayed until after the event, it can be changed later.

@CiscoFrisco What bullet points? Are you sure you're not just seeing the GitHub icon?

> Still about the "Regulation" button, I personally prefer it when the tags are around the div instead of the inner text although this is being picky

@pedrogneto Sorry, I don't really get what you're referring to

**Comment by CiscoFrisco** [comment]
@pedromsfernandes Don't know if you can see it in this photo but there are some bullet points for each winner.

image

**Comment by pedromsfernandes** [comment]
> @pedromsfernandes Don't know if you can see it in this photo but there are some bullet points for each winner.

Wow, I'm all blind. It's fixed now

**Review by CiscoFrisco — APPROVED** [review]

**Review by EstevesAndre — APPROVED** [review]
Good to go!

**Pull request merged**
